runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|css|json|jazz))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|css|json|jazz))

- url: /js
  static_dir: js
     
- url: /
  static_files: home.html
  upload: home.html

- url: .*
  script: main.py

